### ISSUE TITLE
Optional quality parameter

### ISSUE THREAD

**Issue by midzer** [jakewarren/smartcrop-cli#1]
Hi,
this tool might come in handy :)

How about allowing an optional parameter to specify image quality for `.jpg` images?
I'm fairly new to golang but I would be happy to open a PR if you like.

Cheers
midzer

**Comment by jakewarren** [comment]
@midzer I think that's a great idea. I should have thought of that instead of just hard-coding it.. :)

**Comment by jakewarren** [comment]
added via #3 by @midzer
